name: Build & Deploy Auth Service

on:
  push:
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EUREKA_URL: ${{ secrets.EUREKA_URL }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: 🚀 SSH and Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            echo "🔄 Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

            echo "🛑 Stopping and removing old container if exists..."
            docker stop auth-service || true
            docker rm auth-service || true

            echo "🚀 Running updated container..."
            docker run -d --name auth-service \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e EUREKA_URL=${{ secrets.EUREKA_URL }} \
              -p 8081:8081 \
              ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
