name: Build & Deploy Wallet Service

on:
  push:
    paths:
      - 'Wallet_system/**'
      - '.github/workflows/wallet-service-deploy.yml'
  workflow_dispatch:
   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EUREKA_URL: ${{ secrets.EUREKA_URL }}
      KAFKA_URL: ${{ secrets.KAFKA_URL }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧪 Build JAR with Maven
        run: mvn clean package -DskipTests
        working-directory: ./Wallet_system

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./Wallet_system
          file: ./Wallet_system/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wallet-service:latest

      - name: 🚀 SSH and Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            bash <<EOF
            echo "🔄 Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/wallet-service:latest

            echo "🛑 Stopping and removing old container if exists..."
            docker stop wallet-service || true
            docker rm wallet-service || true

            echo "🚀 Running updated container..."
            docker run -d --name wallet-service \
              -e DB_URL="${DB_URL}" \
              -e DB_USERNAME="${DB_USERNAME}" \
              -e DB_PASSWORD="${DB_PASSWORD}" \
              -e JWT_SECRET="${JWT_SECRET}" \
              -e EUREKA_URL="${EUREKA_URL}" \
              -e KAFKA_URL="${KAFKA_URL}" \
              -p 8083:8083 \
              ${{ secrets.DOCKER_USERNAME }}/wallet-service:latest
            EOF

